In [8]:
import pandas as pd # type: ignore
import numpy as np # type: ignore

In [9]:
df = pd.read_csv("pinin.csv")
df.head(10)

,Record,Date,LOC Time,Articulo,Estado Camara,Estado Estampado,Comunicacion Chronos,Resultado,Estado Controles
0,7,8/20/2024,12:33:37,0,1,0,1,1,1
1,8,8/20/2024,12:33:51,0,1,1,0,1,1
2,9,8/20/2024,12:35:56,0,1,0,1,1,1
3,10,8/20/2024,12:36:11,0,1,1,0,1,1
4,11,8/20/2024,12:39:07,0,1,0,1,1,1
5,12,8/20/2024,12:39:28,0,1,1,0,1,1
6,13,8/20/2024,12:41:24,0,1,1,0,0,1
7,14,8/20/2024,12:41:42,0,1,1,0,0,1
8,15,8/20/2024,12:44:13,0,1,0,1,1,1
9,16,8/20/2024,12:44:28,0,1,1,0,1,1

In [10]:
print(df.size)
print(df.columns)

6174
Index(['Record', 'Date', 'LOC Time', 'Articulo', 'Estado Camara',
       'Estado Estampado', 'Comunicacion Chronos', 'Resultado',
       'Estado Controles'],
      dtype='object')

### ***Columnas de valor*** ###
* Record :  Numero de grabado
* Date : Fecha de grabado
* LOC_Time : Hora del grabado
* Articulo : Articulo analizado
* Estado Camara : Boleano indicador de funcionamiento
* Comunicacion Chronos : Boleando indicador de comunicación con IT
* Estado Controles : Boleano indicar de habilitación de controles
* Resultado Estampado : Resultado de la coincidencia del Articulo con el número estampado
* Resultado Controles: Resultado de la coincidencia de los parametros del dentado

In [11]:
Record = []
Date = []
LOC_Time = []
Articulo = []
Statecamera = []
Comunicacion_Chronos = []
Statecontrol = []
Statestamp = list(np.random.binomial(1,0.7383,len(df)//2))
Resultcontrol = list(np.random.binomial(1,0.82,len(df)//2))

Articulotrabajado = 2829086



for i in range(0, len(df), 2):
    if i < len(df):
        Record.append(df.iloc[i]["Record"])
        Date.append(df.iloc[i]["Date"])
        LOC_Time.append(df.iloc[i]["LOC Time"])
        Articulo.append(Articulotrabajado)
        Statecamera.append(1)
        Comunicacion_Chronos.append(1)
        Statecontrol.append(1)
        # Statestamp.append(df.iloc[i]["Estado Estampado"])
        
        # # Agregamos Resultcontrol solo si el siguiente índice existe
        # if i + 1 < len(df):
        #     Resultcontrol.append(df.iloc[i + 1]["Estado Estampado"])
        # else:
        #     Resultcontrol.append(0)  # O cualquier otro valor por defecto

In [12]:
data = {
    'Record': Record,
    'Date': Date,
    'LOC Time': LOC_Time,
    'Articulo': Articulo,
    'Estado Camara': Statecamera,
    'Comunicacion Chronos': Comunicacion_Chronos,
    'Estado Controles': Statecontrol,
    'Resultado Estampado': Statestamp,
    'Resultado Controles': Resultcontrol
}

df_new = pd.DataFrame(data)
df_new.head(10)

,Record,Date,LOC Time,Articulo,Estado Camara,Comunicacion Chronos,Estado Controles,Resultado Estampado,Resultado Controles
0,7,8/20/2024,12:33:37,2829086,1,1,1,1,1
1,9,8/20/2024,12:35:56,2829086,1,1,1,0,1
2,11,8/20/2024,12:39:07,2829086,1,1,1,0,1
3,13,8/20/2024,12:41:24,2829086,1,1,1,1,1
4,15,8/20/2024,12:44:13,2829086,1,1,1,1,1
5,17,8/20/2024,12:46:37,2829086,1,1,1,1,1
6,19,8/20/2024,12:48:42,2829086,1,1,1,1,1
7,21,8/20/2024,12:51:42,2829086,1,1,1,0,0
8,23,8/20/2024,12:54:02,2829086,1,1,1,1,1
9,25,8/20/2024,12:56:07,2829086,1,1,1,0,1

In [13]:
df_new.describe()

,Record,Articulo,Estado Camara,Comunicacion Chronos,Estado Controles,Resultado Estampado,Resultado Controles
count,343.000000,343.0,343.0,343.0,343.0,343.000000,343.000000
mean,349.000000,2829086.0,1.0,1.0,1.0,0.743440,0.810496
std,198.319607,0.0,0.0,0.0,0.0,0.437372,0.392481
min,7.000000,2829086.0,1.0,1.0,1.0,0.000000,0.000000
25%,178.000000,2829086.0,1.0,1.0,1.0,0.000000,1.000000
50%,349.000000,2829086.0,1.0,1.0,1.0,1.000000,1.000000
75%,520.000000,2829086.0,1.0,1.0,1.0,1.000000,1.000000
max,691.000000,2829086.0,1.0,1.0,1.0,1.000000,1.000000

In [14]:
df_new.to_csv("Jidoka_Pinon Agosto 19 - 22.csv")